---
cloud_service_group: Applications
cloud_service_type: Application
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    type: count
    options:
      default: 0
